apiVersion: v1
kind: Service
metadata:
  name: sm-notification-center
  namespace: sm
  labels:
    app: sm-notification-center
    platform: sm-suite
spec:
  type: ClusterIP
  selector:
    app: sm-notification-center
  ports:
  - name: http
    port: 8470
    targetPort: http
    protocol: TCP
