apiVersion: v2
name: sm-notification-center
description: 通知中心 Helm Chart（SM 企业级微服务部署资产）
type: application
version: 1.0.0
appVersion: "2.1.0"
keywords:
  - sm-microservices
  - enterprise
maintainers:
  - name: sm-platform-team
